version: '3'
services:
 your-app-service:
  build:
   context: ../.
   dockerfile: docker/your-app/Dockerfile.dev
  container_name: your-app_dev  #service dev name
  volumes:
  - ../:/app                    #setting volume to dev container