FROM python:3.6-slim-stretch

RUN apt-get -y update
RUN apt-get install -y --fix-missing \
    build-essential \
    cmake \
    gfortran \
    git \
    wget \
    curl \
    graphicsmagick \
    libgraphicsmagick1-dev \
    libatlas-dev \
    libavcodec-dev \
    libavformat-dev \
    libgtk2.0-dev \
    libjpeg-dev \
    liblapack-dev \
    libswscale-dev \
    pkg-config \
    python3-dev \
    python3-numpy \
    software-properties-common \
    zip \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*

# Clone dlib
RUN cd ~ && \
    mkdir -p dlib && \
    git clone -b 'v19.9' --single-branch https://github.com/davisking/dlib.git dlib/ && \
    cd  dlib/ && \
    python3 setup.py install --yes USE_AVX_INSTRUCTIONS

# Set workd dir and copy requirements.txt to container
WORKDIR /app
# Copy requirements.txt to configured workdir (/app)
COPY docker/requirements.txt .

# Installs dependecies added in requirements.txt
RUN pip3 install -r requirements.txt

# Considering that you cloned this repository in a directory  inside your app / project (yourApp / docker /)
# This command copy all itens in your app directory to container in configured workdir (/ app)
COPY ././. .